# Reversations
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/slepper-api/reservations/prodution',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/slepper-api/reservations/prodution',
      ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/slepper-api/auth/prodution',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'southamerica-east1-docker.pkg.dev/slepper-api/auth/prodution']

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/slepper-api/notifications/prodution',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/slepper-api/notifications/prodution',
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/slepper-api/payments/prodution',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/slepper-api/payments/prodution',
      ]
